// Copyright 2026 Küstenlogik
// SPDX-License-Identifier: Apache-2.0

using Microsoft.AspNetCore.Http;

namespace Kuestenlogik.Bowire.Endpoints;

/// <summary>
/// The <c>?workspaceId=</c> / <c>?storageRoot=</c> pair every per-workspace
/// endpoint reads, validated once.
/// </summary>
/// <remarks>
/// <para>
/// Both values end up in a file path, and both arrive from a query string —
/// which CodeQL flagged as <c>cs/path-injection</c> and which is simply true:
/// nothing between the browser and <c>Path.Combine</c> was checking them.
/// Six endpoint files read this pair, so the check belongs here rather than
/// six times over, where the seventh would be the one that forgot.
/// </para>
/// <para>
/// The threat is not hypothetical even for a tool bound to loopback. A page
/// in any tab can POST to <c>localhost</c>, and Bowire's own workbench runs
/// scripts from the target APIs it renders. "It only listens locally" bounds
/// who can reach it, not what a request can ask for once it does.
/// </para>
/// </remarks>
internal static class WorkspaceScopeQuery
{
    /// <summary>A validated scope, or the reason it was refused.</summary>
    /// <param name="WorkspaceId">Null when the caller named none.</param>
    /// <param name="StorageRoot">Null when the caller named none.</param>
    /// <param name="Error">Null when the scope is usable.</param>
    internal readonly record struct Scope(string? WorkspaceId, string? StorageRoot, string? Error)
    {
        /// <summary>True when the request named something this server will not act on.</summary>
        public bool IsInvalid => Error is not null;
    }

    /// <summary>
    /// Read and validate the pair from a request.
    /// </summary>
    internal static Scope From(HttpContext ctx)
    {
        ArgumentNullException.ThrowIfNull(ctx);

        var workspaceId = ctx.Request.Query["workspaceId"].ToString();
        var storageRoot = ctx.Request.Query["storageRoot"].ToString();
        return Validate(workspaceId, storageRoot);
    }

    /// <summary>
    /// The rules, separated from <see cref="HttpContext"/> so they can be
    /// exercised directly.
    /// </summary>
    internal static Scope Validate(string? workspaceId, string? storageRoot)
    {
        var id = string.IsNullOrWhiteSpace(workspaceId) ? null : workspaceId.Trim();
        var root = string.IsNullOrWhiteSpace(storageRoot) ? null : storageRoot.Trim();

        if (id is not null && !IsSafeSegment(id))
        {
            return new Scope(null, null,
                "workspaceId must be a single path segment: letters, digits, dot, dash or underscore.");
        }

        if (root is not null)
        {
            // Absolute, because a relative root resolves against the server's
            // working directory — which is not something the caller can see
            // and not something they meant to write into.
            if (!Path.IsPathRooted(root))
                return new Scope(null, null, "storageRoot must be an absolute path.");

            // '..' is refused before normalisation rather than after: a root
            // is a location the operator chose, and one that has to climb out
            // of itself to mean something is not that.
            if (root.Split(['/', '\\']).Any(s => s == ".."))
                return new Scope(null, null, "storageRoot must not contain '..'.");

            // A workspace root is a directory the operator already pointed
            // Bowire at. Requiring it to exist is what stops a request from
            // naming somewhere arbitrary and having the server create it —
            // the difference between writing into a folder someone chose and
            // writing into one the request invented.
            if (!Directory.Exists(root))
                return new Scope(null, null, "storageRoot does not name an existing directory.");
        }

        return new Scope(id, root, null);
    }

    /// <summary>
    /// Whether <paramref name="value"/> is usable as one path segment.
    /// </summary>
    /// <remarks>
    /// An allow-list, not a deny-list. Workspace ids are generated by the
    /// workbench and look like <c>ws-3f2a9c</c>; anything outside that shape
    /// is a request doing something other than naming a workspace, and
    /// enumerating what to forbid would mean keeping up with separators,
    /// alternate encodings and reserved device names on three platforms.
    /// </remarks>
    private static bool IsSafeSegment(string value)
    {
        if (value.Length == 0 || value.Length > 128) return false;
        if (value == "." || value == "..") return false;

        foreach (var c in value)
        {
            var ok = char.IsAsciiLetterOrDigit(c) || c == '.' || c == '-' || c == '_';
            if (!ok) return false;
        }

        return true;
    }
}
