import { chromium } from '@playwright/test';
const browser = await chromium.launch();
const page = await browser.newPage();
page.setDefaultTimeout(8000);
await page.goto('http://localhost:5177/', { waitUntil: 'domcontentloaded' });
await page.evaluate(() => { try { localStorage.clear(); sessionStorage.clear(); } catch {} });
await page.reload({ waitUntil: 'domcontentloaded' });
await page.waitForSelector('#bowire-app.bowire-app-ready', { timeout: 25000 });
await page.waitForSelector('#bowire-loading', { state: 'detached', timeout: 5000 }).catch(() => {});
await page.locator('#bowire-welcome-create-btn').click();
await page.waitForSelector('.bowire-ws-create-dialog .bowire-prompt-input');
await page.locator('.bowire-ws-create-dialog .bowire-prompt-input').first().fill('Flow Probe');
const tpl = page.locator('.bowire-ws-create-dialog [data-tpl-id="empty"]');
if (await tpl.count()) await tpl.click();
await page.locator('.bowire-ws-create-dialog .bowire-confirm-btn:not(.cancel)').click();
await page.waitForTimeout(2000);
const sel = '.bowire-rail-btn[data-rail-mode-id="flows"]';
await page.locator(sel).click().catch(() => {});
await page.waitForTimeout(600);
console.log('A) same session, right after creating the first workspace :', await page.evaluate(() => localStorage.getItem('bowire_rail_mode')));
await page.reload({ waitUntil: 'domcontentloaded' });
await page.waitForSelector('#bowire-app.bowire-app-ready', { timeout: 25000 });
await page.waitForSelector('#bowire-loading', { state: 'detached', timeout: 5000 }).catch(() => {});
await page.locator(sel).click().catch(e => console.log('   click failed:', e.message.split('\n')[0]));
await page.waitForTimeout(600);
console.log('B) after a reload                                          :', await page.evaluate(() => localStorage.getItem('bowire_rail_mode')));
await browser.close();
