// Copyright 2026 Küstenlogik
// SPDX-License-Identifier: Apache-2.0

namespace Kuestenlogik.Bowire.Flows.Expectations;

/// <summary>
/// Outcome of evaluating a single <see cref="FlowExpectation"/> against a
/// <see cref="FlowRequestEnvelope"/>. Carries enough detail for the UI
/// result viewer + T2's JUnit XML failure messages to be useful without a
/// re-evaluation pass.
/// </summary>
public sealed class FlowExpectationResult
{
    /// <summary>Mirrors the source expectation's <see cref="FlowExpectation.Id"/>.</summary>
    public string? Id { get; init; }

    /// <summary>True when the expectation held.</summary>
    public bool Passed { get; init; }

    /// <summary>What the kind+target resolved to in the envelope, stringified.</summary>
    public string? Actual { get; init; }

    /// <summary>Echo of the expectation's right-hand side, post variable substitution.</summary>
    public string? Expected { get; init; }

    /// <summary>One-line summary suitable for JUnit XML / UI result rows ("status equals 200 — got 404").</summary>
    public string Message { get; init; } = string.Empty;

    /// <summary>Source kind, echoed for downstream filtering (latency-only rollups, …).</summary>
    public FlowExpectationKind Kind { get; init; }

    /// <summary>Source operator, echoed for the same reason.</summary>
    public FlowExpectationOperator Operator { get; init; }
}

/// <summary>
/// Per-step rollup: all expectation results for one Flow step, plus
/// pass/fail counts that callers can read without iterating.
/// </summary>
public sealed class FlowStepExpectationResult
{
    /// <summary>Step identifier — the in-flow node id.</summary>
    public string StepId { get; init; } = string.Empty;

    /// <summary>Count of expectations that held.</summary>
    public int Passed { get; init; }

    /// <summary>Count of expectations that did not hold.</summary>
    public int Failed { get; init; }

    /// <summary>Per-expectation detail in declaration order.</summary>
    public IReadOnlyList<FlowExpectationResult> Evaluations { get; init; } = Array.Empty<FlowExpectationResult>();

    /// <summary>True when no expectations failed (vacuously true for empty <see cref="Evaluations"/>).</summary>
    public bool AllPassed => Failed == 0;
}

/// <summary>
/// Per-flow rollup. Aggregates step results into the top-level summary
/// the v2.2 CLI runner prints + ships into JUnit XML.
/// </summary>
public sealed class FlowExpectationRollup
{
    /// <summary>Source flow identifier.</summary>
    public string FlowId { get; init; } = string.Empty;

    /// <summary>Run identifier — opaque, generated by the caller, propagates into JUnit so reruns are addressable.</summary>
    public string RunId { get; init; } = string.Empty;

    /// <summary>Total expectations that held across every step.</summary>
    public int Passed { get; init; }

    /// <summary>Total expectations that did not hold across every step.</summary>
    public int Failed { get; init; }

    /// <summary>Sum of <see cref="Passed"/> and <see cref="Failed"/>.</summary>
    public int TotalEvaluations => Passed + Failed;

    /// <summary>Wall-clock duration of the whole flow run, in milliseconds.</summary>
    public long DurationMs { get; init; }

    /// <summary>Per-step detail in execution order.</summary>
    public IReadOnlyList<FlowStepExpectationResult> Steps { get; init; } = Array.Empty<FlowStepExpectationResult>();

    /// <summary>True when no step had a failing expectation.</summary>
    public bool AllPassed => Failed == 0;
}
