// Copyright 2026 Küstenlogik
// SPDX-License-Identifier: Apache-2.0

using Kuestenlogik.Bowire.Mocking;
using Microsoft.OpenApi;
using Microsoft.OpenApi.Reader;
using Microsoft.OpenApi.YamlReader;

namespace Kuestenlogik.Bowire.Protocol.Rest.Mock;

/// <summary>
/// Phase 3d: turns a parsed OpenAPI document into a synthetic
/// <see cref="BowireRecording"/> so the standard mock pipeline
/// (matcher + replayer + chaos + stateful mode) can replay the API
/// without any captured traffic. Each operation becomes one step whose
/// response body is generated by <see cref="OpenApiSampleGenerator"/>.
/// </summary>
public static class OpenApiRecordingBuilder
{
    /// <summary>
    /// Load an OpenAPI document from <paramref name="path"/> and build a
    /// synthetic recording covering every operation. Throws
    /// <see cref="InvalidDataException"/> when the document is missing,
    /// malformed, or has no paths.
    /// </summary>
    public static async Task<BowireRecording> LoadAsync(string path, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(path))
            throw new ArgumentException("Schema path is required.", nameof(path));
        if (!File.Exists(path))
            throw new FileNotFoundException($"Schema file not found: {path}", path);

        await using var stream = File.OpenRead(path);

        // Microsoft.OpenApi.Readers ships a JSON reader by default; YAML
        // requires an explicit registration. Add it unconditionally —
        // the cost is negligible and users expect `.yaml`/`.yml` inputs
        // to "just work" next to `.json`.
        var settings = new OpenApiReaderSettings();
        settings.AddYamlReader();

        var format = InferFormat(path);
        var readResult = await OpenApiDocument.LoadAsync(stream, format, settings, ct);

        if (readResult?.Document is null)
            throw new InvalidDataException($"Schema file '{path}' did not parse as a valid OpenAPI document.");

        var doc = readResult.Document;
        if (doc.Paths is null || doc.Paths.Count == 0)
            throw new InvalidDataException($"Schema file '{path}' has no paths.");

        return Build(doc, path);
    }

    /// <summary>
    /// Test-friendly overload — build a recording from an in-memory
    /// <see cref="OpenApiDocument"/>.
    /// </summary>
    public static BowireRecording Build(OpenApiDocument doc, string sourceLabel)
    {
        var recording = new BowireRecording
        {
            Id = "schema-only",
            Name = doc.Info?.Title ?? "schema-only",
            Description = $"Generated from OpenAPI schema '{sourceLabel}'. " +
                          "Responses are synthesised from the schema; override by capturing real recordings.",
            CreatedAt = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds(),
            RecordingFormatVersion = Kuestenlogik.Bowire.Mock.Loading.RecordingFormatVersion.Current
        };

        var stepNumber = 1;
        foreach (var (path, pathItem) in doc.Paths)
        {
            if (pathItem.Operations is null) continue;

            foreach (var (verb, operation) in pathItem.Operations)
            {
                var (schema, statusCode) = PickSuccessResponseSchema(operation);

                var step = new BowireRecordingStep
                {
                    Id = "schema_" + stepNumber.ToString(System.Globalization.CultureInfo.InvariantCulture),
                    Protocol = "rest",
                    Service = PickService(operation, doc),
                    Method = !string.IsNullOrEmpty(operation.OperationId)
                        ? operation.OperationId
                        : verb.ToString().ToUpperInvariant() + " " + path,
                    MethodType = "Unary",
                    HttpPath = path,
                    HttpVerb = verb.ToString().ToUpperInvariant(),
                    Status = statusCode,
                    // No schema on the success response (204 endpoints,
                    // handlers that only declare a status code, ...) —
                    // leave the body empty so the replayer doesn't
                    // emit text into a no-body status like 204.
                    Response = schema is null ? null : OpenApiSampleGenerator.Generate(schema)
                };

                recording.Steps.Add(step);
                stepNumber++;
            }
        }

        if (recording.Steps.Count == 0)
        {
            throw new InvalidDataException(
                $"Schema '{sourceLabel}' parsed but yielded zero operations.");
        }

        return recording;
    }

    // Pick the first 2xx response with a JSON-shaped schema. Falls back
    // to the first 2xx response regardless of content-type (so an empty
    // 204 still produces a step), and finally to "200" with no schema.
    private static (IOpenApiSchema? Schema, string Status)
        PickSuccessResponseSchema(OpenApiOperation operation)
    {
        if (operation.Responses is null) return (null, "OK");

        foreach (var (code, response) in operation.Responses)
        {
            if (!code.StartsWith('2')) continue;
            if (response.Content is null) continue;

            foreach (var (contentType, mediaType) in response.Content)
            {
                if (mediaType.Schema is null) continue;
                if (string.Equals(contentType, "application/json", StringComparison.OrdinalIgnoreCase) ||
                    contentType.Contains("+json", StringComparison.OrdinalIgnoreCase))
                {
                    return (mediaType.Schema, code);
                }
            }
        }

        foreach (var (code, _) in operation.Responses)
        {
            if (code.StartsWith('2')) return (null, code);
        }

        return (null, "OK");
    }

    // Pass the format explicitly so the reader doesn't have to sniff the
    // first byte: files ending in .yaml/.yml go to the YAML reader, .json
    // to the JSON reader, everything else is left to the default sniff.
    private static string? InferFormat(string path)
    {
        var ext = Path.GetExtension(path);
        if (string.Equals(ext, ".yaml", StringComparison.OrdinalIgnoreCase) ||
            string.Equals(ext, ".yml", StringComparison.OrdinalIgnoreCase))
        {
            return "yaml";
        }
        if (string.Equals(ext, ".json", StringComparison.OrdinalIgnoreCase))
        {
            return "json";
        }
        return null;
    }

    private static string PickService(OpenApiOperation operation, OpenApiDocument doc)
    {
        if (operation.Tags is { Count: > 0 } tags)
        {
            foreach (var t in tags)
            {
                if (t?.Name is { Length: > 0 } name) return name;
            }
        }
        return doc.Info?.Title ?? "Default";
    }
}
